name: Test Single Scraper

on:
  workflow_dispatch:
    inputs:
      scraper_name:
        description: 'Scraper name (e.g. "GitHub Trending") or type (e.g. "hackernews")'
        type: string
        required: true

jobs:
  run:
    uses: ./.github/workflows/_pipeline.yml
    with:
      table_suffix: "_test"
      run_mode: "test"
      scraper_name: ${{ inputs.scraper_name }}
    secrets: inherit
